export const REQUEST_PENDING = 'REQUEST_PENDING';
export const FETCHING_ERROR = 'FETCHING_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
